version: "3.4"

volumes:
  argonms-volume:

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      # NOTE: we're not forwarding this port to the host. Adminer on port 8080
      # should suffice for most administration, but modify this to 3306:3306 if
      # you need to access the database locally
      - 3306
    volumes:
      - argonms-volume:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_TYPE=mysql
      - ADMINER_DEFAULT_PORT=3306
      - ADMINER_DEFAULT_DB=${MYSQL_DATABASE}
  center:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      # create a new target volume and copy the container defaults into it
      - /app/target
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    depends_on:
      - db
    ports:
      - "8383:8383"
    command: >
      bash -c "
        sleep 5 &&
        bin/run_sql.sh < sql/argon.sql &&
        bin/run_sql.sh < sql/default_reactor_drops.sql &&
        bin/run_sql.sh < sql/default_shops.sql &&
        bin/run_sql.sh < sql/default_cash_shop.sql &&
        bin/launch_center.sh
      "
  login: &server
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      - ${DATA_DIR?data directory not configured}:/app/wz
      - /app/target
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - DATA_DIR=wz/
      - SCRIPT_DIR
      - ARGONMS_HOST=${ARGONMS_HOST:-localhost}
    depends_on:
      - center
      - db
    ports:
      - "8484:8484"
    command: bash -c "sleep 15 && bin/launch_login.sh"
  game:
    <<: *server
    ports:
      - "7575:7575"
    command: bash -c "sleep 15 && bin/launch_game.sh"
  shop:
    <<: *server
    ports:
      - "8787:8787"
    command: bash -c "sleep 15 && bin/launch_shop.sh"
